-- Create an Orchestration Schema to keep things clean
CREATE SCHEMA IF NOT EXISTS DBT_WORKSPACES.ORCHESTRATION;

-- 1. THE ROOT TASK (The "Brain")
-- This triggers the graph. Pros use a dedicated warehouse for orchestration.
CREATE OR REPLACE TASK DBT_WORKSPACES.ORCHESTRATION.DAILY_PIPELINE_ROOT
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = 'USING CRON 0 1 * * * Australia/Sydney' -- 1 AM local time
    COMMENT = 'Enterprise Root Task: Triggers Nightly dbt Build'
AS
    SELECT CURRENT_TIMESTAMP(); -- Root tasks can be simple dummy actions

-- 2. THE SYNC TASK
-- Pulls the latest code from your separate dbt repo
CREATE OR REPLACE TASK DBT_WORKSPACES.ORCHESTRATION.SYNC_GIT_RESOURCES
    WAREHOUSE = 'COMPUTE_WH'
    AFTER DBT_WORKSPACES.ORCHESTRATION.DAILY_PIPELINE_ROOT
AS
    ALTER GIT REPOSITORY DBT_WORKSPACES.WORKSPACE_DEV.SF_DBT_DEMO1_REPO FETCH;

-- 3. THE EXECUTION TASK
-- The actual dbt build
CREATE OR REPLACE TASK DBT_WORKSPACES.ORCHESTRATION.RUN_DBT_MODELS
    WAREHOUSE = 'COMPUTE_WH'
    AFTER DBT_WORKSPACES.ORCHESTRATION.SYNC_GIT_RESOURCES
AS
    EXECUTE DBT PROJECT DBT_WORKSPACES.WORKSPACE_DEV.SF_DBT_DEMO1 
      args='build --target prod';

-- 4. THE MONITORING TASK (Pros always alert on success/fail)
-- This sends a notification to a Snowflake Alert or Error Integration
CREATE OR REPLACE TASK DBT_WORKSPACES.ORCHESTRATION.NOTIFY_COMPLETION
    WAREHOUSE = 'COMPUTE_WH'
    AFTER DBT_WORKSPACES.ORCHESTRATION.RUN_DBT_MODELS
AS
    CALL SYSTEM$SEND_EMAIL(
        'DBT_MONITORING_INTEGRATION',
        'data-ops@yourcompany.com',
        'DBT Run Success',
        'The nightly dbt build completed successfully at ' || CURRENT_TIMESTAMP()
    );


ALTER TASK DBT_WORKSPACES.ORCHESTRATION.NOTIFY_COMPLETION RESUME;
ALTER TASK DBT_WORKSPACES.ORCHESTRATION.RUN_DBT_MODELS RESUME;
ALTER TASK DBT_WORKSPACES.ORCHESTRATION.SYNC_GIT_RESOURCES RESUME;
ALTER TASK DBT_WORKSPACES.ORCHESTRATION.DAILY_PIPELINE_ROOT RESUME;

-- To do: set up notification Integration